# Generated by Django 5.2.6 on 2025-09-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('maquinaria', models.CharField(max_length=255)),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'db_table': 'lecturas',
            },
        ),
    ]
